orderServer:
  replicaCount: 1
  image:
    repository: rash77/shopogolik-order:v0.2.0
    pullPolicy: Always
  port: 8000
  portName: order-shopsvc
  targetPort: 8000
  host: arch.homework
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

orderSub:
  replicaCount: 1
  image:
    repository: rash77/shopogolik-order-sub:v0.1.0
    pullPolicy: Always

db:
  port: 5432
  replicaCount: 1
  name: postgres-order
  dbName: order_db
  mountPath: /var/lib/postgresql/data
  image:
    repository: bitnami/postgresql
    pullPolicy: Always

  volume:
    storage: 1Gi
    path: /data/postgres

  secret:
    user: cG9zdGdyZXM=
    pass: cGFzc3dvcmQ=

broker:
  host: kafka-service
  port: 9092

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
