apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.secret.user }} # printf postgres | base64
  POSTGRES_PASSWORD: {{ .Values.db.secret.pass }} # printf password | base64
