apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.db.volume.storage }}
  hostPath:
    path: {{ .Values.db.volume.path }}
  storageClassName: standard
