version: '3'

services:
  sub:
    container_name: order-sub
    build: 
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - .:/code

networks:
  shop_network:
    driver: bridge
