version: '3'

services:
  backend:
    container_name: order-shop
    build: 
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - .:/code
    ports:
      - '8002:8000'

networks:
  shop_network:
    driver: bridge
