version: '3'

services:
  backend:
    container_name: shopogolik
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres:15.0-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata 
