
db:
  port: 5432
  replicaCount: 1
  mountPath: /var/lib/postgresql/data
  image:
    repository: bitnami/postgresql
    pullPolicy: Always

  volume:
    storage: 1Gi
    path: /data/postgres

  secret:
    user: cG9zdGdyZXM=
    pass: cGFzc3dvcmQ=

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
