apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logistic-ingress-ping
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.logisticServer.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.logisticServer.port }}
        path: /api/v1/logistic/ping/
        pathType: Exact
