apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: {{ .Release.Name}}-dp
  name: {{ .Release.Name}}-dp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name}}-dp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name}}-dp
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: shopogolik-cm
              key: db_name
        - name: POSTGRES_HOST
          value: {{ .Release.Name}}-db
        - name: POSTGRES_PORT
          value: {{ .Values.db.port | quote}}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-credentials
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: server-credentials
              key: superuser
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-credentials
              key: superuser_pwd

        image: {{ .Values.server.image.repository }}
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        name: {{ .Release.Name}}-dp
        resources: {}
          # limits:
          #   memory: 2Gi
          #   cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
