apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.authServer.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name}}
            port:
              number: {{ .Values.authServer.port }}
        path: /login
        pathType: Prefix
