apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: {{ .Values.zookeeper.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.targetPort }}