apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopogolik
  labels:
    team: metrics-demo-monitor
    
spec:
  endpoints:
    - port: shopport
      scrapeTimeout: 30s
      path: /metrics     
      honorLabels: true
      scheme: http
#  jobLabel: stack
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: shopogolik
