apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    role: service
spec:
  selector:
    app: {{ .Chart.Name }}
    role: service
  type: NodePort
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
