apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    role: service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      role: service
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        role: service
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: {{ .Chart.Name }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ .Chart.Name }}
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shopogolik-cm
                  key: db_name
          ports:
            - containerPort: {{ .Values.port }}
              name: {{ .Chart.Name }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: {{ .Values.mountPath }}
      volumes:
        - name: {{ .Chart.Name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}
