apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress-ping
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.paymentServer.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name}}
            port:
              number: {{ .Values.paymentServer.port }}
        path: /api/v1/payment/ping/
        pathType: Exact
