apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 2147483647
  replicas: {{ .Values.notifyServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: {{ .Values.db.dbName }}
        - name: POSTGRES_HOST
          value: {{ .Values.db.host }}
        - name: POSTGRES_PORT
          value: {{ .Values.db.port | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: notify-postgres-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: notify-postgres-credentials
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: notify-server-credentials
              key: superuser
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notify-server-credentials
              key: superuser_pwd

        image: {{ .Values.notifyServer.image.repository }}
        imagePullPolicy: {{ .Values.notifyServer.image.pullPolicy }}
        name: {{ .Release.Name }}
        ports:
        - name: {{ .Values.notifyServer.portName }}
          containerPort: {{ .Values.notifyServer.port }}
        resources: {}
          # limits:
          #   memory: 2Gi
          #   cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
