apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.authServer.port }}
    name: {{ .Values.authServer.portName }}
    targetPort: {{ .Values.authServer.targetPort }}
  type: NodePort