
grafana:
  enabled: true
  adminPassword: "admin"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.homework
